{{- range $cronjobName, $cronjob := .Values.cronjobs  }}
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ $.Values.appname }}-{{ $cronjobName }}
  labels:
    {{- include "chart.labels" $ | nindent 4 }}
spec:
  schedule: {{ $cronjob.schedule | quote }}
  concurrencyPolicy: {{ default "Replace" $cronjob.concurrencyPolicy }}
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  startingDeadlineSeconds: 300
  jobTemplate:
    metadata:
      labels:
        app.kubernetes.io/instance: {{ $.Values.appname }}-{{ $cronjobName }}
        {{- include "chart.selectorLabels" $ | nindent 8 }}
    spec:
      backoffLimit: {{ default 0 $cronjob.backoffLimit }}
      ttlSecondsAfterFinished: 900
      template:
        metadata:
          labels:
            app.kubernetes.io/instance: {{ $.Values.appname }}-{{ $cronjobName }}
            {{- include "chart.selectorLabels" $ | nindent 12 }}
        spec:
          restartPolicy: Never
          serviceAccountName: default
          {{- with $cronjob.podSecurityContext }}
          securityContext:
            {{- toYaml $cronjob.podSecurityContext | nindent 12 }}
          {{- end }}
          {{- with $.Values.hostAliases }}
          hostAliases:
            {{- toYaml $.Values.hostAliases | nindent 12 }}
          {{- end }}
          terminationGracePeriodSeconds: {{ default 30 $cronjob.terminationGracePeriodSeconds }}
          containers:
            - name: {{ $cronjobName }}
              command:
                {{- toYaml $cronjob.command | nindent 16 }}
              envFrom:
                - secretRef:
                    name: {{ $.Values.appname }}-env
              env:
                {{- if hasKey $.Values "env" }}
                {{- range $index, $element := $.Values.env }}
                - name: {{ $index | quote }}
                  value: {{ $element | quote }}
                {{- end }}
                {{- end }}
                {{- if hasKey $cronjob "env" }}
                {{- range $index, $element := $cronjob.env }}
                - name: {{ $index | quote }}
                  value: {{ $element | quote }}
                {{- end }}
                {{- end }}
              {{- if hasKey $cronjob "imageTag" }}
              image: {{ printf "%s/%s:%s" $.Values.registry $.Values.appname $cronjob.imageTag }}
              {{- else }}
              image: {{ include "chart.image" $ }}
              {{- end }}
              imagePullPolicy: IfNotPresent
              resources:
                {{- toYaml $cronjob.resources | nindent 16 }}
              volumeMounts:
                {{- range $volumeMount := $.Values.volumeMounts  }}
                - name: {{ default "secret" $volumeMount.name }}
                  mountPath: {{ $volumeMount.mountPath }}
                  {{- if hasKey $volumeMount "subPath" }}
                  subPath: {{ $volumeMount.subPath }}
                  {{- end }}
                {{- end }}
          volumes:
            - name: secret
              secret:
                secretName: {{ $.Values.appname }}-secret
{{- end }}
