{{- range $ingress := .Values.ingresses -}}
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ $ingress.host | replace "." "-" }}-{{ $.Values.cluster }}-ein-plus
  annotations:
    kubernetes.io/ingress.class: lain-internal
  labels:
    {{- include "chart.labels" $ | nindent 4 }}
spec:
  rules:
    - host: {{ $ingress.host }}.{{ $.Values.cluster }}.ein.plus
      http:
        paths:
        {{- range $ingress.paths }}
          - path: {{ . }}
            backend:
              serviceName: {{ $.Values.appname }}-{{ $ingress.deployName }}
              servicePort: 80
        {{- end }}

{{- end -}}
